export default function TermsAndConditions() {
  return (
    <div className="min-h-screen">
      <div className="prose lg:prose-xl max-w-none">
        <h1 className="text-4xl font-bold mb-6">Terms and Conditions</h1>
        <p className="text-lg">Last Updated: August 14, 2025</p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">
          1. Introduction
        </h2>
        <p>
          Welcome to Writoma (&quot;we,&quot; &quot;our,&quot; or &quot;us&quot;). These Terms and Conditions (&quot;Terms&quot;) govern your use of the Writoma website and our AI Human Detector and AI Detector tool (collectively, the &quot;Service&quot;). By accessing or using our Service, you agree to be bound by these Terms. If you disagree with any part of the terms, then you do not have permission to access the Service.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">
          2. Description of Service
        </h2>
        <p>
          Writoma provides a Software-as-a-Service (SaaS) platform that allows users to analyze text to detect whether it was generated by an AI or a human. The service is provided on an &quot;as is&quot; and &quot;as available&quot; basis. We are constantly changing and improving our Service. We may add or remove functionalities or features, and we may suspend or stop a Service altogether.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">
          3. User Accounts
        </h2>
        <p>
          When you create an account with us, you guarantee that the information you provide us is accurate, complete, and current at all times. Inaccurate, incomplete, or obsolete information may result in the immediate termination of your account on our Service. You are responsible for safeguarding the password that you use to access the Service and for any activities or actions under your password.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">
          4. Acceptable Use
        </h2>
        <p>You agree not to use the Service:</p>
        <ul className="list-disc list-inside space-y-2">
          <li>In any way that violates any applicable national or international law or regulation.</li>
          <li>For the purpose of exploiting, harming, or attempting to exploit or harm minors in any way.</li>
          <li>To transmit, or procure the sending of, any advertising or promotional material, including any &quot;junk mail&quot;, &quot;chain letter,&quot; &quot;spam,&quot; or any other similar solicitation.</li>
          <li>To impersonate or attempt to impersonate Writoma, a Writoma employee, another user, or any other person or entity.</li>
          <li>To engage in any other conduct that restricts or inhibits anyone&apos;s use or enjoyment of the Service, or which, as determined by us, may harm Writoma or users of the Service or expose them to liability.</li>
        </ul>

        <h2 className="text-2xl font-semibold mt-8 mb-4">
          5. Intellectual Property
        </h2>
        <p>
          The Service and its original content (excluding Content provided by users), features and functionality are and will remain the exclusive property of Writoma and its licensors. Our trademarks and trade dress may not be used in connection with any product or service without the prior written consent of Writoma.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">
          6. User Content
        </h2>
        <p>
          Our Service allows you to post, link, store, share and otherwise make available certain information, text, graphics, or other material (&quot;Content&quot;). You are responsible for the Content that you post on or through the Service, including its legality, reliability, and appropriateness. By posting Content on or through the Service, you grant us the right and license to use, modify, publicly perform, publicly display, reproduce, and distribute such Content on and through the Service for the purpose of operating and improving the service. You retain any and all of your rights to any Content you submit.
        </p>
        <p>
          We do not claim ownership of your Content. However, by submitting content, you grant us a license to use it to improve our service. We will not use your content for any other purpose.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">
          7. Subscriptions and Payment
        </h2>
        <p>
          Some parts of the Service are billed on a subscription basis (&quot;Subscription(s)&quot;). You will be billed in advance on a recurring and periodic basis (&quot;Billing Cycle&quot;).
        </p>
        <p>
          At the end of each Billing Cycle, your Subscription will automatically renew under the exact same conditions unless you cancel it or Writoma cancels it. You may cancel your Subscription renewal either through your online account management page or by contacting Writoma customer support.
        </p>
        <p>
          A valid payment method, including credit card, is required to process the payment for your Subscription. You shall provide Writoma with accurate and complete billing information including full name, address, state, zip code, telephone number, and a valid payment method information. By submitting such payment information, you automatically authorize Writoma to charge all Subscription fees incurred through your account to any such payment instruments.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">
          8. Termination
        </h2>
        <p>
          We may terminate or suspend your account and bar access to the Service immediately, without prior notice or liability, under our sole discretion, for any reason whatsoever and without limitation, including but not limited to a breach of the Terms.
        </p>
        <p>
          If you wish to terminate your account, you may simply discontinue using the Service.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">
          9. Disclaimer of Warranties; Limitation of Liability
        </h2>
        <p>
          Our Service is provided &quot;as is.&quot; Writoma and its suppliers and licensors hereby disclaim all warranties of any kind, express or implied, including, without limitation, the warranties of merchantability, fitness for a particular purpose and non-infringement. Neither Writoma nor its suppliers and licensors, makes any warranty that the Service will be error free or that access thereto will be continuous or uninterrupted. You understand that you download from, or otherwise obtain content or services through, the Service at your own discretion and risk.
        </p>
        <p>
          In no event will Writoma, or its suppliers or licensors, be liable with respect to any subject matter of this agreement under any contract, negligence, strict liability or other legal or equitable theory for: (i) any special, incidental or consequential damages; (ii) the cost of procurement for substitute products or services; (iii) for interruption of use or loss or corruption of data.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">
          10. Governing Law
        </h2>
        <p>
          These Terms shall be governed and construed in accordance with the laws of the jurisdiction in which the company is established, without regard to its conflict of law provisions.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">
          11. Changes to Terms
        </h2>
        <p>
          We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material we will provide at least 30 days&apos; notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">
          12. Contact Us
        </h2>
        <p>
          If you have any questions about these Terms, please contact us at:
        </p>
        <p>Email: support@writoma.com</p>
      </div>
    </div>
  );
}
